yolo_model:

  config_file:
    name: yolo_lidar.cfg
  weight_file:
    name: yolo_lidar.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - SUV
      - Sedan
      - pedestrian
      - traffic sign 

